# Generated by Django 5.0.14 on 2026-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_country_remove_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='return_type',
            field=models.CharField(choices=[('NONE', 'None'), ('REFUND', 'Get Return Money'), ('REPLACE', 'Replace Product')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
