# Generated by Django 5.0.14 on 2026-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L,XL', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Hrazm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.TextField(blank=True, default='', help_text='Comma-separated image URLs for product slider gallery'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'Clothing & Sportswear'), ('shoes', 'Shoes & Footwear'), ('equipment', 'Sports Equipment & Gear'), ('accessories', 'Accessories & Bags')], default='clothing', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
