# Generated by Django 5.0.14 on 2026-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_is_active_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery_images',
            field=models.TextField(blank=True, default='', help_text='Comma-separated image URLs for gallery slider'),
        ),
    ]
