# Generated by Django 5.0.14 on 2026-09-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_gender_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_images',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
