# Generated by Django 5.0.14 on 2026-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_item',
            field=models.TextField(blank=True, default='', help_text='Enter bullet points separated by newlines'),
        ),
        migrations.AddField(
            model_name='product',
            name='age_range',
            field=models.CharField(blank=True, default='Adult', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='construction_type',
            field=models.CharField(blank=True, default='Hand-stitched', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='7.2 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='item_weight',
            field=models.CharField(blank=True, default='399 Grams', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Leather', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stitching_type',
            field=models.CharField(blank=True, default='Hand-stitched', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_in_the_box',
            field=models.TextField(blank=True, default='1 x Sports Gear'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, default='White,Red', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_images',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('equipment', 'Equipment'), ('accessories', 'Accessories')], default='clothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
